### ISSUE TITLE
webui.sh and DOCKERFILE still reference old GitHub location

### ISSUE THREAD

**Issue by mmairs** [nullpointer-io/stablediffusion-webui-docker#1]
for DejaVuSans.ttf and "git clone".

**Comment by nullpointer-io** [comment]
Hi mmairs. Thanks for the hint. I will try the new URL tomorrow:
https://github.com/sd-webui/stable-diffusion-webui

**Comment by nullpointer-io** [comment]
@mmairs Fixed with v0.9.1. Thanks again.
